version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: always
#    volumes:
#      - /home/user/Desktop/db:/var/lib/mysql
    ports:
      - "3336:3306"  # Chạy MySQL trên port 3336 của máy host
    environment:
      MYSQL_DATABASE: sep490v5
      MYSQL_ROOT_PASSWORD: Dtvuvu1522002
      MYSQL_ROOT_HOST: "%"  # Cho phép remote access
    networks:
      - mynetwork

  rabbitmqq:
    container_name: rabbitmqq
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"    # RabbitMQ Port
      - "15672:15672"  # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mynetwork

  redis:
    container_name: redis
    image: redis:latest
    restart: always
#    command: [ "redis-server", "--requirepass", "vuvu15202" ]
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  springboot-app:
    container_name: backend
    image: sep490
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
      - rabbitmqq
      - redis
    ports:
      - "8088:8088"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: Dtvuvu1522002
      MYSQL_PORT: 3306  # Cổng của MySQL trong container (không phải 3336)
      MYSQL_DATABASE: sep490v5
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
